name: Run Mabl Tests from CSV File

on:
  workflow_dispatch:

jobs:
  get-test-ids:
    runs-on: ubuntu-latest
    outputs:
      test_ids: ${{ steps.get_ids.outputs.test_ids }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Mabl Data from CSV
  id: get_data
  run: |
    # Read the CSV file, skipping the header.
    CSV_DATA=$(tail -n +2 mabl_data.csv)
    
    # Process each line to create a valid JSON object, trimming any whitespace.
    MATRIX_JSON=$(echo "$CSV_DATA" | awk -F',' '{print "{\"test_id\":\""$1"\", \"environment_id\":\""$2"\"}"}' | jq -s . | tr -d '\n')
    
    echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  mabl-local:
    runs-on: ubuntu-latest
    needs: get-test-ids
    strategy:
      matrix:
        test_id: ${{ fromJSON(needs.get-test-ids.outputs.test_ids) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mabl CLI
        run: npm install -g @mablhq/mabl-cli

      - name: Run Test Locally
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          
          echo "Running Test ID: ${{ matrix.test_id }}"
          mabl auth activate-key ${{ secrets.MABL_API_KEY }}
          
          xvfb-run mabl tests run --id ${{ matrix.test_id }} --environment-id RH4FfeHgfnxiHFJyKkPsmQ-e